### PR TITLE
Fix NumericDatePicker Crash When Out-of-range Date is Selected

### LINKED ISSUE #567: Fix NumericDatePicker bug
A Bug in the NumericDatePicker class which sometimes causes crash when one selects a date out of the range of allowed dates (min and max dates)

### PR DESCRIPTION
**Pull request by qiarie**
Fixes #567

### CODE REVIEW

File: android-json-form-wizard/src/main/java/com/vijay/jsonwizard/customviews/NumericDatePicker.java [hunk 1]
```diff
@@ -86,7 +87,7 @@ protected void resetDatePicker() {
             switch (violation) {
                 case MALFORMED_DATE:
                     // Only Day can malform since different months have different days in the Gregorian calendar
```
Comment (ndegwamartin) [inline android-json-form-wizard/src/main/java/com/vijay/jsonwizard/customviews/NumericDatePicker.java:89]: We can remove this comment, the month could potentially lead to this state as well

File: android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/DateUtil.java [hunk 2]
```diff
@@ -117,4 +115,8 @@ public static String getDuration(long timeDiff, Locale locale, Context context)
         return duration;
 
     }
+
+    public static boolean isLeapYear(int year) {
+        return ((year % 4 == 0) && (year % 100 != 0)) || year % 400 == 0;
```
Comment (ndegwamartin) [inline android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/DateUtil.java:120]: We can use the helper method`com.vijay.jsonwizard.utils.NumericDatePickerHelper#isLeapYear` instead

**Comment by ndegwamartin** [comment]
@qiarie to close #577 we need to : 

- [ ] Make the PR to both the `v1` and the `master` branch
- [ ] Bump up the aritfact version

**Review by ndegwamartin — APPROVED** [review]
