### PR TITLE
Remove Empty Value Check for LengthValidator

### LINKED ISSUE #634: Adding Max Length Validation For a Text Field That is Not Required Still Checks for Empty Value
When `v_max_length` validation is added to text fields that do not have `v_required` set or value explicitly set to `false`, and no value is set before submitting the form, the field's validation fails.

For text fields not marked as mandatory, extra validation should only apply when there's a value entered, i.e., field is not empty.

### PR DESCRIPTION
**Pull request by qiarie**
Resolves #634

### CODE REVIEW

File: android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java [hunk 1]
```diff
@@ -18,8 +18,7 @@ public LengthValidator(String errorMessage, int minLength, int maxLength) {
 
     @Override
     public boolean isValid(CharSequence charSequence, boolean isEmpty) {
```
Comment (ndegwamartin) [inline android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java:20]: What if we used the `isEmpty` boolean to return `true` since it is a parameter passed by the super to tell whether the text is empty?

Alternatively we can update the constructor to include an `isRequired` flag and then check that to make the validation check. That way it is also invalid if the _isRequired_ is **true** and char sequence is empty

Comment (ndegwamartin) [reply android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java:20]: Actually I think we can update the constructor to include an `isRequired` flag and then check that to make the validation check. That way it is also invalid if the _isRequired_ is **true** and char sequence is empty

Comment (qiarie) [reply android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java:20]: This is noted.
I think the `isEmpty` flag sent to the validator is redundant since we check for the field's length when doing the other checks for min and max length validators. `isEmpty` flag may also mean different things for mandatory or non-mandatory fields, or in case of a minimum length greater than zero.

Comment (qiarie) [reply android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java:20]: Also bundling a required validator for this may have unintended results when forms are not properly defined.

Comment (ndegwamartin) [reply android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java:20]: The _isRequired_ field could then be populated to `true` if in the json form filed _**it exists**_ and **_it is set to true_** otherwise `false`

Comment (ndegwamartin) [reply android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/LengthValidator.java:20]: The _isRequired_ field could then be populated to `true` if in the json form field _**it exists**_ and **_it is set to true_** otherwise `false`

**Review by ndegwamartin — APPROVED** [review]
